googledatastudio/tooling

templates/community-viz/package.json
Quick temporary fix to ensure template continues to use updated library.
=> updated dscc version

package.json, src/files.ts, src/util.ts, templates/community-connector/package.json, yarn.lock
And fix issue where node_modules were being overwritten.
=> Update connector deps

README.md
---
- Adds badges: https://shields.io
- Format notes into callouts
=> docs: Update README with badges, note callouts

templates/viz/README.md
the README is now out of date. fixed.
=> updated README

templates/viz/package.json, templates/viz/src/index.js, templates/viz/yarn.lock
corresponding edits to update codelab
=> template edits

packages/dscc-gen/templates/viz/package.json, packages/dscc-gen/templates/viz/yarn.lock
=> modified package + yarn.lock for new version of dscc.scripts

.travis.yml, packages/dscc-gen/test.sh, packages/dscc-scripts/test.sh, test.sh
added set -ex to the bash scripts so they fail as soon as they encounter an error. Also moved the `cd`s to be at the top-level so the `test.sh` scripts can be run locally.
=> Updated test scripts to fail early.

packages/dscc-scripts/src/viz/schemas.ts, packages/dscc-scripts/test/viz/util.spec.ts
=> Add default value for selectSingle & selectRadio

packages/dscc-scripts/src/util.ts, packages/dscc-scripts/src/viz/schemas.ts, packages/dscc-scripts/src/viz/util.ts, packages/dscc-scripts/test/viz/util.spec.ts
Update validation interface to support objects (for js scripts using this library), or filePaths (for bash, etc scripts using this library)
=> Clean up validation interface

packages/ds-component/src/index.ts, packages/ds-component/src/types.ts
update license & add to types file.
=> license fix

packages/dscc-validation/src/schemas.ts, packages/dscc-validation/test/index.spec.ts
edited test + schema to reflect defaultValue change
=> edited schemas and validation

packages/dscc-gen/package.json, packages/dscc-gen/src/config.ts
Also add in some convenience scripts to dscc-gen.
=> Change back internal names to bucket so code works again.

packages/dscc-validation/src/schemas.ts, packages/dscc-validation/test/index.spec.ts
=> adding textarea

packages/ds-component/__tests__/impl.test.ts, packages/ds-component/src/index.ts
- support for identity function (with warning)
- modified arbitrary function test to not be identity function
- tests that identity function throws warning
=> added support & warning for identity function

packages/ds-component/__tests__/impl.test.ts, packages/ds-component/package.json, packages/ds-component/src/index.ts, packages/ds-component/yarn.lock
remove urlparse to remove dependencies
=> removed urlparse

packages/ds-component/__tests__/impl.test.ts, packages/ds-component/package.json, packages/ds-component/src/index.ts, packages/ds-component/src/types.ts, packages/ds-component/tsconfig.json, packages/ds-component/yarn.lock
Should fix the [bug] not returning comparison tables for objectFormat.
- fixed objectFormat types
- added COMPARISON tables to tests
- fixed bug in objectFormat parsing
[bug]: https://github.com/googledatastudio/tooling/issues/140
=> Fix comparison tables bug

packages/dscc-gen/templates/viz/package.json
=> updated ds-component version

packages/dscc-scripts/src/viz/build.ts, packages/dscc-scripts/src/viz/message.ts
- Leverages built in functionality of CopyWebpackPlugin to transform the manifest and write the new file destination.
- Allows the entire build process to be handled by Webpack.
=> Use CopyWebpackPlugin to copy manifest

packages/dscc-gen/package.json, packages/dscc-gen/src/config.ts, packages/dscc-gen/src/prompt.ts, packages/dscc-gen/src/types.ts, packages/dscc-gen/src/viz/index.ts, packages/dscc-gen/templates/viz-ts/README.md, packages/dscc-gen/templates/viz-ts/dist/index.html, packages/dscc-gen/templates/viz-ts/package.json, packages/dscc-gen/templates/viz-ts/src/index.css, packages/dscc-gen/templates/viz-ts/src/index.json, packages/dscc-gen/templates/viz-ts/src/index.ts, packages/dscc-gen/templates/viz-ts/src/localMessage.ts, packages/dscc-gen/templates/viz-ts/src/manifest.json, packages/dscc-gen/templates/viz-ts/tsconfig.json, packages/dscc-gen/templates/viz-ts/webpack.config.js, packages/dscc-gen/templates/viz/package.json, packages/dscc-gen/test/viz/index.spec.ts, packages/dscc-gen/yarn.lock, packages/dscc-scripts/package-lock.json, packages/dscc-scripts/package.json, packages/dscc-scripts/src/util.ts, packages/dscc-scripts/src/viz/build.ts, packages/dscc-scripts/src/viz/message.ts, packages/dscc-scripts/src/viz/util.ts, packages/dscc-scripts/test/viz/util.spec.ts, packages/dscc-scripts/tsconfig.json, packages/dscc-scripts/viz/initialViz.d.ts
- Removes codelab option that doesn't exist anymore.
- Adds TypeScript template for viz creation.
=> Add viz TypeScript template

packages/dscc-gen/src/config.ts, packages/dscc-gen/src/connector/index.ts, packages/dscc-gen/src/types.ts, packages/dscc-gen/templates/connector-ts/src/PATH_USER_PASS_auth.ts, packages/dscc-gen/templates/connector-ts/src/global.d.ts, packages/dscc-gen/templates/connector/src/PATH_USER_PASS_auth.js
Adds support for https://developers.google.com/datastudio/connector/auth#path_user_pass
* Adds new option for Path & User & Pass on connector creation in TS/JS
* Adds to existing enum
* Adds new request interface
=> Add PathUserPass auth type.
